### ISSUE TITLE
Spell correction - Principals of a well designed application

### ISSUE THREAD

**Issue by paparthi** [MicrosoftDocs/feedback#2712]
*Describe the bug**
The title reads "Principals of a well designed application" instead of "Principles of ...".

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/azure/architecture/

**Expected behavior**
It is a minor update to a title.

**Screenshots**

![image](https://user-images.githubusercontent.com/7234198/80718737-2659e180-8ac0-11ea-8230-cea468aba9a4.png)

**Comment by gewarren** [comment]
@paparthi Thank you!

**Comment by JasonWHowell** [comment]
@gewarren is this resolved now? `#please-close` if so.

**Comment by gewarren** [comment]
It's not fixed quite yet for some reason. I created a new PR.
