### ISSUE TITLE
break link in PowerShell Module Browser

### ISSUE THREAD

**Issue by ToMakeSense** [MicrosoftDocs/feedback#2750]
Break link in [Azure Service Management PowerShell Module Reference ](https://docs.microsoft.com/en-us/powershell/module/?view=azuresmps-4.0.0)
![image](https://user-images.githubusercontent.com/6244148/75016094-31433500-54c5-11ea-8e5b-cb2335d3b496.png)

Break link can be find for **`Azure`** Module (https://docs.microsoft.com/en-us/powershell/module/Azure/?view=azuresmps-4.0.0), the actual URL is: https://docs.microsoft.com/en-us/powershell/azure/servicemanagement/overview?view=azuresmps-4.0.0

It's better to get it referenced, even Azure module(ASM) is out of date and hardly used any more.

**You can find the originally posted below for requesting to create this new issue**:
> _Originally posted by @nschonni in https://github.com/MicrosoftDocs/feedback/issues/1574#issuecomment-503826103_
> _Originally posted by @e0i in https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1100#issuecomment-628809254_

**Comment by JasonWHowell** [comment]
@mikefrobbins is this something you could investigate?

**Comment by mikefrobbins** [comment]
This issue has been resolved and can be closed.

**Comment by JasonWHowell** [comment]
#please-close

**Comment by nschonni** [comment]
https://docs.microsoft.com/en-us/powershell/module/?view=azuresmps-4.0.0 still shows the break in the original screenshot

**Comment by nschonni** [comment]
Nevermind, this was about the target, and not the formatting of the unlinked "Module" word
