### ISSUE TITLE
Many apis show arguments with TBD

### ISSUE THREAD

**Issue by shooshx** [MicrosoftDocs/feedback#543]
**Describe the bug**
Just a few I noticed today:
https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-drawtextexa
https://docs.microsoft.com/en-us/windows/desktop/api/wingdi/nf-wingdi-getstockobject
https://docs.microsoft.com/en-us/windows/desktop/api/wingdi/nf-wingdi-exttextouta

**To Reproduce**
1. Go to the above addresses

**Expected behavior**
arguments would be documented as they always were

**Comment by Powerhelmsman** [comment]
@ginami Please take a look at this issue.

**Comment by Derpalus** [comment]
I noticed this earlier here: https://github.com/MicrosoftDocs/feedback/issues/493
Still not fixed one month later.

**Comment by shooshx** [comment]
TBD: fix TBDs

**Comment by ginami** [comment]
Hi @shooshx -- the TBDs in the pages you listed in your initial comment have been fixed. Thank you for bringing this issue to our attention.

**Comment by shooshx** [comment]
@ginami 
The TBD issue seem to be gone in these specific pages but here are a few APIs that still have problems in their argument description in the form of strange OPTIONAL placeholder:

https://docs.microsoft.com/en-us/windows/desktop/api/clfsw32/nf-clfsw32-reserveandappendlog
https://docs.microsoft.com/en-us/windows/desktop/api/ktmw32/nf-ktmw32-createtransactionmanager
https://docs.microsoft.com/en-us/windows/desktop/api/dsgetdc/nf-dsgetdc-dsderegisterdnshostrecordsw
https://docs.microsoft.com/en-us/windows/desktop/api/winhttp/nf-winhttp-winhttpopenrequest

Here are some that still have TBD:
https://docs.microsoft.com/en-us/windows/desktop/api/wininet/nf-wininet-internetsetoptionexw
https://docs.microsoft.com/en-us/windows/desktop/api/winineti/nf-winineti-internetsetdialstatew
https://docs.microsoft.com/en-us/windows/desktop/api/advpub/nf-advpub-extractfilesw
https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-lookupaccountsidlocalw
https://docs.microsoft.com/en-us/windows/desktop/api/workspaceruntime/nf-workspaceruntime-iworkspacescriptable3-startworkspaceex2

Are we having fun? I think this is fun.
What wizardry is this you ask? oh, it's called Google, you should try it too:

https://www.google.co.il/search?q=TBD+site:https://docs.microsoft.com/en-us/windows/desktop/api/&safe=off&ei=Cq99W77iH5K6aeL_prAC&start=10&sa=N&biw=1767&bih=892

Otherwise, we can just continue to do this the same way, you fix 4 pages, then I find 4 more, etc', I good with that as well.

**Comment by ginami** [comment]
Thanks @shooshx -- yep, this is an ongoing migration issue and will continue to be on our radar until all are fixed.

**Comment by shooshx** [comment]
This ongoing migration issue sounds more like a python script that needs better error checking. You already had someone fixing it, couldn't they do the minimum verification that the output doesn't include the string "TBD"?

**Comment by gsa-nerds** [comment]
So? any news on when this is going to addressed?
