### ISSUE TITLE
API Reference rendering bug when resizing browser

### ISSUE THREAD

**Issue by conceptdev** [MicrosoftDocs/feedback#729]
**Describe the bug**

At certain browser widths, the *In this article* link list is duplicated. This only happens for API reference, does not occur when resizing conceptual pages.

**To Reproduce**

1. Go to any reference page. e.g. [system.collections.generic](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic?view=netcore-2.1)
2. Resize the width of the browser
3. Observe the *In this article* menu. When the browser is between 1090 and 1200 pixels wide, there are **TWO** instances of that menu (screenshots below).

**Expected behavior**

The *In this article* menu should move from inline to the right column. There should not be two copies.

**Screenshots**

![screen shot 2018-10-03 at 11 01 17 am](https://user-images.githubusercontent.com/199373/46430571-33ed9080-c6fe-11e8-8e76-1d6dd6dca57b.png)
![screen shot 2018-10-03 at 11 01 10 am](https://user-images.githubusercontent.com/199373/46430573-36e88100-c6fe-11e8-8f50-b7e3589f2408.png)
![screen shot 2018-10-03 at 11 01 01 am](https://user-images.githubusercontent.com/199373/46430577-38b24480-c6fe-11e8-9396-16f7bba50bcc.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.12 Sierra
 - Browser: Safari, Chrome, Firefox
 - Version: 12, 69.0.3497.100, 61.0.2

 - OS: Windows 10
 - Browser: Edge, IE
 - Version: 42.17134.1.0, 11.285.17134.0

**Comment by racha999** [comment]
@

**Comment by Powerhelmsman** [comment]
@ShevaDas Can you take a look at this issue?

**Comment by svick** [comment]
This looks like a duplicate of https://github.com/MicrosoftDocs/feedback/issues/665, which was closed as fixed yesterday.

**Comment by conceptdev** [comment]
(yep, same issue) how long should it take for the fix to be public? Still occurring today:
 
![duplicate-lists](https://user-images.githubusercontent.com/199373/46544497-9bc7e680-c878-11e8-997d-bfe028af8ac9.png)

**Comment by ShevaDas** [comment]
@conceptdev I'm not seeing it today. If you do see it on any pages, it'll be fixed by doing a content rebuild. Please double check and then close this out if it's looking good for you too.

**Comment by ShevaDas** [comment]
@conceptdev I'm going to close this out. Feel free to re-open if it's not fixed for you.

**Comment by conceptdev** [comment]
@ShevaDas I am still seeing it, here's a screenshot from an incognito window (although i'm working on a new computer, so i don't think it could be a caching issue regardless). this is macOS & Chrome:

<img width="1169" alt="duplicate-ita" src="https://user-images.githubusercontent.com/199373/46758351-76c0e280-cc81-11e8-834e-7670841d2599.png">
