### ISSUE TITLE
Microsoft Learning / Techprofile login is broken

### ISSUE THREAD

**Issue by JEPauley** [MicrosoftDocs/feedback#828]
I have been attempting to complete training on Microsoft Learning for Azure learning paths but have been unable to login to the application for the past 4-5 days.   When navigate to the learning path and attempt to sign-in it takes me to the techprofile page and not to a login dialog.     

I already have a techprofile with my account which I have completed sessions on but I have no way to login and continue the courses.   Its disappointing that something as simple as a login can be so messed up.   

No error codes, etc.  You need to get your DevOps team onto this and determine why logins are failing, I'm certain I'm not the only individual who is having the problem and others may simply give up and go to something that works like AWS or Google Cloud.

Thanks,

James

**Comment by JamesPauleyJr** [comment]
Any update on this bug?  I'm 100% blocked on any Microsoft Learning courses for Azure.  I've tried different browsers, clearing cache data but the process to signing to Microsoft learning continues to lead me to the create a profile page for TechProfile.   My account is James.Pauley@Sojournis.com

**Comment by Mei-Liang** [comment]
@JEPauley, sorry to hear about the issue. Could you please help clarify a few things:
1. You are signing using Azure Active Directory organization account. not Microsoft Account, correct? 
2. What's your profile url, for example: https://techprofile.microsoft.com/en-US/mliang 
3. When did you create your tech profile, after creating the profile, were you able to sign in at least once?

Thanks
Mei

**Comment by JEPauley** [comment]
1] I believe I'm signing in using AAD, (james.pauley@sojournis.com) provisioned @ godaddy.com
2] https://techprofile.microsoft.com/en-us/jamespauleyjr
3] Yes, I created a tech profile and completed several learning modules before it started to have this bug/behavior.

**Comment by Sampy** [comment]
When you go to sign in with an In Private/Incognito browser, is this the flow that you see?

1. Click Sign In on a Learn page
2. Navigate to a login.live.com URL where you enter your email (james.pauley@sojournis.com)
3. You are then sent to a login.microsoftonline.com URL to enter your password
4. After you do, you are redirected to the TechProfile registration screen and asked to select a user name and display name.

Does that match up with what is happening when you try to login?

**Comment by JEPauley** [comment]
1.  Click Sign In on a Learn page
  2.  Navigate to a login.live.com URL where you enter your email (james.pauley@sojournis.com<mailto:james.pauley@sojournis.com>)
     *   yes
  3.  You are then sent to a login.microsoftonline.com URL to enter your password
     *   No
     *   Re-directed to GoDaddy Office 365 sign-in. – enter password
     *   Directed to learn page of lesson plan I had URL for & logged in with my profile.
  4.  After you do, you are redirected to the TechProfile registration screen and asked to select a user name and display name.
Something seems to have changed to make it function?

**Comment by JamesPauleyJr** [comment]
I was able to login and access the training modules under my tech profile “jamespauleyjr”.

However, once into the module and working on exercises, I receive an “Unable to provision Azure resources.”  This is an issue different from logging it but can it be related somehow?

Best Regards,

James

**Comment by JEPauley** [comment]
When I tried to login with a “normal” browser session, I end up with the create techprofile page when I try to login to the learning site.

**Comment by ibakirov** [comment]
@JEPauley you are not alone with **_“Unable to provision Azure resources"_** The same here in #846 :(
Whenever you login into @learn.docs.microsoft.com directory in Azure Portal (https://portal.azure.com/#@learn.docs.microsoft.com) and try to create manually any vm for example, do you see any error?

I got this:
![screenshot_2018-11-13 microsoft azure](https://user-images.githubusercontent.com/7983476/48436801-dee77480-e7a9-11e8-82ce-218b14e9761f.png)

**Comment by ibakirov** [comment]
> My issues is slightly different now. I am able to login to the Microsoft learning (docs.microsoft.com) however, when I try to start a module I am receiving an “unable to provision Azure resources” error. Previously I had two directories, my personal and a learning directory on Azure, but now I don’t’ see the learning based directory. 

My problem is the same, I can't start sandbox and get the same error "unable to provision Azure resources"

**Comment by Mei-Liang** [comment]
@yunyunyunyun could you please look at the issue now, @JEPauley is able to login but got "unable to provision Azure resources” error. @ibakirov has same issue.

**Comment by njenekar** [comment]
My issue is I don't see Concierge Subscription when trying to create new Cosmos DB account getting below message,
You are currently signed into the 'learn.docs.microsoft.com' directory which does not have any subscriptions. You have other directories you can switch to or you can sign up for a new subscription.

**Comment by njenekar** [comment]
> My issue is I don't see Concierge Subscription when trying to create new Cosmos DB account getting below message,
> You are currently signed into the 'learn.docs.microsoft.com' directory which does not have any subscriptions. You have other directories you can switch to or you can sign up for a new subscription.

I tried with New Incognito Window, it solves my issue, getting Concierge Subscription for Sandbox.

**Comment by ibakirov** [comment]
@njenekar I was already working in Incognito mode from the beginning. Really I didn't matter and does not resolve the issue.

Sandbox reset itself and today after my try I successfully activated sandbox with re-accepting sandbox invitation. I really didn't try on two week holidays, that's magic :) **Boguslaw Buczek** confirms that sandbox reset by itself and got working too: https://social.microsoft.com/Forums/en-US/68f262b3-86d5-4be5-a343-711cfea1b446/solved-sandbox-does-not-activate-on-microsoft-learn-units?forum=CertGeneral

Thanks for assistance!

@JEPauley if you don't mind issue may be closed.

**Comment by rpentyBI** [comment]
Hey, is there a fix for this
whenever i try to create a sandbox i get this error "Unable to provision Azure resources"
![image](https://user-images.githubusercontent.com/47373470/52315024-bde28a00-297a-11e9-8088-0e781b23f72a.png)

**Comment by ibakirov** [comment]
@rpentyBI there might some problems on Azure site, please try to check again. Last night got some problems too and they gone themselves.

**Comment by nickparlow** [comment]
i get exactly the same problem as @rpentyBI when i sign in with my work account. when i sign in with my personal account everything is fine, i can create a sandbox and a vm.

**Comment by Sampy** [comment]
In some cases, Azure Active Directory accounts (what our sites sometimes call "Work/School Accounts") may have problems using the Azure Sandbox. There are a variety of reasons related to security and directory configuration. A personal Microsoft Account should always work.

**Comment by TNDStudios** [comment]
Am having the same issue when logging in to complete a course, I get the create profile screen (Create profile to save progress) but when entering my details there are a number of errors in the background when hitting the register button. The main one is a 400 response from 

404 error from https://docs.microsoft.com/api/profiles/me
400 error from https://docs.microsoft.com/api/profiles stating:

{errorCode: "CpmContentException", message: "Invalid contact point"}
errorCode: "CpmContentException"
message: "Invalid contact point"

I have tried with multiple email addresses and other combinations with the same result each time.

**Comment by TNDStudios** [comment]
Note, I just found out if you don't agree to the terms it lets you in, if you do agree to the terms it does not .. Seems weird, no?

**Comment by ValentinCalomme** [comment]
Been having similar issues. When I click on "sign in", I am automatically redirected to the registration page, although I already have an account. Tried multiple browsers in incognito mode and not, and nothing works so far.

**Comment by MortenMeisler** [comment]
This is my experience, tried Edge and Chrome:
![loginissue](https://user-images.githubusercontent.com/17620242/56213773-f5e20980-605c-11e9-9a73-3ba28fd97b30.gif)

**Comment by jaywha** [comment]
What fixed it for me was to use InCognito on Chrome, but then I had to ensure the docs email matched my Azure email which _also_ needed updating (my company uses jwhaley OR jay.whaley).  

## In Azure
Followed this here: https://docs.microsoft.com/en-us/azure/billing/billing-how-to-change-azure-account-profile to make sure it matches the same email I put in the docs field below.

## Inside Learn
I went to here on the top-right
![image](https://user-images.githubusercontent.com/3476458/56226616-34fe6380-6039-11e9-84d5-69e5eec27387.png)
then to here on the left-hand side of the screen
![image](https://user-images.githubusercontent.com/3476458/56226645-45aed980-6039-11e9-9b5b-8b598cefc405.png)
then entered my full name email here
![image](https://user-images.githubusercontent.com/3476458/56226732-80b10d00-6039-11e9-8d95-10cabc65c020.png)

### Results
![image](https://user-images.githubusercontent.com/3476458/56226886-e43b3a80-6039-11e9-97ec-6edb5cef85ec.png)

**Comment by bergmeister** [comment]
I found that changing the Url from `en-gb` to `en-us` makes it work as a temporary workaround, definitely a culture issue

**Comment by ibakirov** [comment]
@bergmeiter I don't so, I also tried before switching from en-us to ru-ru and vice-versa.
Now I do not face this problem anymore

**Comment by chrisrharris** [comment]
I had to use InPrivate for this to work as well.  I already had an Azure Free subscription, but the Microsoft Learning does create a new Learning Sandbox that I can switch to. However, I don't seem to have enough permissions to create resources.  The only way I could get around this was using InPrivate, and this seems to happen for each new lesson Sandbox.

**Comment by chrisrharris** [comment]
I noticed that if I switch back to my default directory, then switch back into the learning directory, the resources appear and permissions are fixed.  No InPrivate/InCognito required.

**Comment by Sharparam** [comment]
Facing the same issue on this page: https://docs.microsoft.com/en-us/learn/modules/store-app-data-with-azure-blob-storage/4-create-storage-resources

 * Using incognito in Chrome does not solve the issue.
 * Changing locale does not solve the issue.
 * Changing directory in the Azure Portal does not solve the issue (the "Learn" directory does not exist since the Learning Path is unable to provision it).
 * I am using my personal Microsoft account and not a work/school account.

**Comment by Sampy** [comment]
We have deployed. We changes to the authentication system on Docs which should address your issues. If not, let us know.
